# -*- coding: utf-8 -*-
"""Connor_agent.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PbcrrUjY8ZA-0O6d_pL0qLT5-v0toCe0
"""

#Connor AI agent - M&A Front Screen
#This tool should NOT be used with confidential or personal data.

!pip install yfinance

def welcome_message():
    print("Hello, I'm Connor . your M&A project assistant.")

def ask_deal_type():
    print("\nFirst question:")
    print("type of M&A deal? (Aquisition, Merger, Divestiture, Other)")
    deal_type = input("Your answer:")
    return deal_type

def ask_industry():
    print("\nSecond question:")
    print("which industry doesn the target operate in?")
    industry = input("Your answer: ")
    return industry

def ask_deal_size():
    print("\nThird question:")
    print("What is the approximate deal size (e.g <50M, 50-200M, 200M-1B, >1B, more)")
    size = input("Your answer: ")
    return size

def ask_risk_level():
    print("\nFourth question")
    print("What is the approximate risk prediction? (High risk, Moderate risk, Low risk)")
    risk = input("your answer: ")
    return risk

def ask_ticker():
    print("\nOptional question:")
    ticker = input("Enter a company stock ticker (e.g., GOOGL, MSFT) or leave blank: ")
    return ticker if ticker else None

def generate_summary(deal_type, industry, deal_size, risk):
    print("\n--- Connor's Summary ---")
    print(f"Deal type: {deal_type}")
    print(f"industry: {industry}")
    print(f"deal size: {deal_size}")
    print(f"Risk level: {risk}")

def generate_recommendation(risk):
    print("\n--- Connor's Recommandation ---")

    if risk.lower() == "high risk":
        print("This deal may require enhanced due diligence and a deeper risk review.")
    elif risk.lower() == "moderate risk":
        print("This deal appears managable but should be monitored closely.")
    elif risk.lower() == "low risk":
        print("This deal seems possible wirth no major red flags.")
    else:
        print("Risk level unclear. Additional information may be required.")

import yfinance as yf

def get_company_info(ticker):
    try:
        data = yf.Ticker(ticker)
        info = data.info
        return {
             "longName": info.get("longName"),
             "sector": info.get("sector"),
             "industry": info.get("industry"),
             "marketCap": info.get("marketCap"),
             "currentPrice": info.get("currentPrice")
        }
    except Exception:
        return None

def main():
    welcome_message()
    print("Let's begin with a few intake questions.")

    deal_type = ask_deal_type()
    print(f"Understood. Deal type recorded as: {deal_type}")

    industry = ask_industry()
    print(f"Industry noted: {industry}")

    deal_size = ask_deal_size()
    print(f"Deal size range captured: {deal_size}")

    risk = ask_risk_level()
    print(f"risk level identified: {risk}")

    # Optional ticker question
    ticker = ask_ticker()

    # Summary + recommendation
    generate_summary(deal_type, industry, deal_size, risk)
    generate_recommendation(risk)

    # Market data section
    if ticker:
       company_data = get_company_info(ticker)
       if company_data:
           print("--- Market Data ---")
           print(f"Company: {company_data['longName']}")
           print(f"Sector: {company_data['sector']}")
           print(f"industry: {company_data['industry']}")
           print(f"Market Cap: {company_data['marketCap']}")
           print(f"Current Price: {company_data['currentPrice']}")
       else:
           print("\nCould not retrieve market data for that ticker.")


if __name__ == "__main__":
    main()